# -*- mode: ruby -*-
# vi: set ft=ruby :
ROOT = File.dirname(File.expand_path(__FILE__))

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = '2'

$base = <<SCRIPT
#!/bin/bash

set -ex
sudo apt-get install -y --no-install-recommends build-essential

SCRIPT

$nodejs = <<SCRIPT
#!/bin/bash

# Note the new setup script name for Node.js v0.10
curl -sL https://deb.nodesource.com/setup_0.10 | sudo bash -

sudo apt-get install -y --no-install-recommends nodejs

sudo npm install -g nodemon

SCRIPT

$mongo = <<SCRIPT
#!/bin/bash

apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
echo "deb http://repo.mongodb.org/apt/ubuntu "$(lsb_release -sc)"/mongodb-org/3.0 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-3.0.list

apt-get update -qq

set -x \
&& apt-get install -y --no-install-recommends mongodb-org \
&& sudo rm -rf /var/lib/apt/lists/*

SCRIPT

$meteor = <<SCRIPT
#!/bin/bash

# Install Meteor
curl -sL https://install.meteor.com/ | sh

SCRIPT

$post = <<SCRIPT

sudo apt-get clean
cat /dev/null > ~/.bash_history && history -c

SCRIPT

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.provision :shell, :inline => $base
  config.vm.provision :shell, :inline => $nodejs
  config.vm.provision :shell, :inline => $mongo
  config.vm.provision :shell, :inline => $meteor

  config.vm.provision :shell, :inline => $post

  config.push.define "atlas" do |push|
    push.app = "thepfmind/meteor-base"
  end

end

# plugin conflict
if Vagrant.has_plugin?("vagrant-vbguest") then
  config.vbguest.auto_update = false
end
